# Dynamic host name completion overlay for nhome.
#
# This file is appended to the script generated by `nhome __completions bash`
# (see flake.nix), which renames the generated function from `_nhome` to
# `_nhome_static` and drops its registration line. Host names cannot be part
# of the generated script because they come from a live `nix eval` of the
# project's flake.nix; this overlay supplies them for the places where a host
# is expected:
#
#   nhome deploy --hosts <HOST>
#   nhome deploy ssh --destination <HOST>
#   nhome ssh [HOST]
#   nhome firewall --hosts <HOST>
#
# Everything else delegates to the generated `_nhome_static` function, and
# hidden internal subcommands are filtered out of its suggestions.

_nhome_root() {
    local i prev_word=""
    for ((i = 1; i < COMP_CWORD; i++)); do
        if [[ "${prev_word}" == "--project-root" ]]; then
            _nhome_root_value="${COMP_WORDS[i]}"
            return 0
        fi
        if [[ "${COMP_WORDS[i]}" == "--project-root="* ]]; then
            _nhome_root_value="${COMP_WORDS[i]#--project-root=}"
            return 0
        fi
        prev_word="${COMP_WORDS[i]}"
    done
    _nhome_root_value="."
}

_nhome_hosts_for_root() {
    local root="$1"
    local now

    now="${EPOCHSECONDS:-$(date +%s)}"

    if [[ -n "${_nhome_hosts_cache_root:-}" && "${_nhome_hosts_cache_root}" == "${root}" \
        && $((now - ${_nhome_hosts_cache_ts:-0})) -lt 60 ]]; then
        COMPREPLY=( $(compgen -W "${_nhome_hosts_cache_list}" -- "${cur}") )
        return 0
    fi

    local hosts
    mapfile -t hosts < <(nhome __hosts --project-root "${root}" 2>/dev/null || true)

    _nhome_hosts_cache_root="${root}"
    _nhome_hosts_cache_ts="${now}"
    _nhome_hosts_cache_list="${hosts[*]}"

    COMPREPLY=( $(compgen -W "${_nhome_hosts_cache_list}" -- "${cur}") )
}

# True when completing the optional host positional of `nhome ssh`.
_nhome_at_ssh_host_position() {
    local i word sub_seen=0 expecting_value=0

    for ((i = 1; i < COMP_CWORD; i++)); do
        word="${COMP_WORDS[i]}"
        if [[ ${expecting_value} -eq 1 ]]; then
            expecting_value=0
            continue
        fi
        case "${word}" in
            --project-root|--command|-c|-b|--build-machine)
                expecting_value=1
                ;;
            -*)
                ;;
            ssh)
                if [[ ${sub_seen} -eq 1 ]]; then
                    return 1
                fi
                sub_seen=1
                ;;
            *)
                return 1
                ;;
        esac
    done

    [[ ${sub_seen} -eq 1 && ${expecting_value} -eq 0 ]]
}

_nhome() {
    local i cur prev filtered=()

    if [[ "${BASH_VERSINFO[0]}" -ge 4 ]]; then
        cur="$2"
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
    fi
    prev="$3"

    # Host name for `--hosts` / `--destination`.
    if [[ "${prev}" == "--hosts" || "${prev}" == "--destination" ]]; then
        _nhome_root
        _nhome_hosts_for_root "${_nhome_root_value}"
        return 0
    fi

    # Host positional of `nhome ssh` (unless completing an option flag).
    if [[ ${cur} != -* ]] && _nhome_at_ssh_host_position; then
        _nhome_root
        _nhome_hosts_for_root "${_nhome_root_value}"
        return 0
    fi

    _nhome_static "$@"

    # Hide the internal subcommands from suggestions.
    for i in "${COMPREPLY[@]}"; do
        if [[ ${i} != __* ]]; then
            filtered+=("${i}")
        fi
    done
    COMPREPLY=("${filtered[@]}")
}

complete -F _nhome nhome
